schema-version = "1.10.0"

[install]
caddy.pkg-path = "caddy"
typescript.pkg-path = "typescript"
nodejs_24.pkg-path = "nodejs_24"
pnpm_10.pkg-path = "pnpm_10"
incus.pkg-path = "incus"
incus.systems = ["aarch64-linux", "x86_64-linux"]
attr.pkg-path = "attr"
attr.systems = ["x86_64-linux", "aarch64-linux"]
qemu_kvm.pkg-path = "qemu_kvm"
